<a href="https://colab.research.google.com/github/JordanBaker78/Data201_JordanBaker/blob/main/class_2_student_notebook_pandas_data_wrangling_for_r_users.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Class 2: pandas Data Wrangling for R Users

**Course:** Data 201-Class 2  
**Background assumed:** R, dplyr pipelines, basic data.frames

---

### How to use this notebook
- Run cells **top to bottom**.
- Complete all **TODO** sections.
- When R code is shown, **translate it to pandas**.
- Focus on clarity and correctness.

## 0. Setup

In [20]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 20)

## 1. From data.frame to DataFrame

In R you might do:
```r
df <- read.csv("data.csv")
```

For today we create a small example dataset.

In [21]:
data = {
    "price": [200, 180, 250, 300, np.nan, 220, 260],
    "size": [1400, 1200, 1600, 1800, 1500, 1550, 1700],
    "bedrooms": [3, 2, 3, 4, 3, 3, 4],
    "neighborhood": ["A", "A", "B", "B", "A", "B", "B"],
}

df = pd.DataFrame(data)
df

   price  size  bedrooms neighborhood
0  200.0  1400         3            A
1  180.0  1200         2            A
2  250.0  1600         3            B
3  300.0  1800         4            B
4    NaN  1500         3            A
5  220.0  1550         3            B
6  260.0  1700         4            B

**TODO:**  
1. Check the **dimensions** of `df`  
2. **Inspect** the structure of `df`  
3. Produce **summary statistics**

In [5]:
df.shape

(7, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         6 non-null      float64
 1   size          7 non-null      int64
 2   bedrooms      7 non-null      int64
 3   neighborhood  7 non-null      object
dtypes: float64(1), int64(2), object(1)
memory usage: 356.0+ bytes

In [7]:
df.describe()

            price         size  bedrooms
count    6.000000     7.000000  7.000000
mean   235.000000  1535.714286  3.142857
std     43.703547   197.303247  0.690066
min    180.000000  1200.000000  2.000000
25%    205.000000  1450.000000  3.000000
50%    235.000000  1550.000000  3.000000
75%    257.500000  1650.000000  3.500000
max    300.000000  1800.000000  4.000000

## 2. Index vs Columns (Very Important!)

**TODO:**  
1. Inspect `df.index`  
2. Inspect `df.columns`  

**Question:** Why is the index *not* the same as a regular column?

In [8]:
df.index
df.columns

Index(['price', 'size', 'bedrooms', 'neighborhood'], dtype='object')

## 3. Selecting Columns (dplyr::select)

In R:
```r
select(df, price, size)
```

**TODO:**  
1. Select only `price` and `size`  
2. Select a single column (`price`) as a **Series**

In [9]:
df[['price', 'size']]

   price  size
0  200.0  1400
1  180.0  1200
2  250.0  1600
3  300.0  1800
4    NaN  1500
5  220.0  1550
6  260.0  1700

In [10]:
df['price']

0    200.0
1    180.0
2    250.0
3    300.0
4      NaN
5    220.0
6    260.0
Name: price, dtype: float64

## 4. Filtering Rows (dplyr::filter)

In R:
```r
filter(df, price > 200)
```

**TODO:**  
1. Filter rows where `price > 200`  
2. Filter rows where `price > 200` **and** `bedrooms >= 3`

In [11]:
df[df['price'] > 200]

   price  size  bedrooms neighborhood
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

In [12]:
df[(df['price'] > 200) & (df['bedrooms'] >= 3)]

   price  size  bedrooms neighborhood
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

In [13]:
df.query('price > 200 and bedrooms >= 3')

   price  size  bedrooms neighborhood
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

## 5. Creating New Variables (dplyr::mutate)

In R:
```r
mutate(df, price_per_sqft = price / size)
```

**TODO:** Create a new column `price_per_sqft`.

In [14]:
df.assign(price_per_bedroom=df['price']/df['bedrooms'])

   price  size  bedrooms neighborhood  price_per_bedroom
0  200.0  1400         3            A          66.666667
1  180.0  1200         2            A          90.000000
2  250.0  1600         3            B          83.333333
3  300.0  1800         4            B          75.000000
4    NaN  1500         3            A                NaN
5  220.0  1550         3            B          73.333333
6  260.0  1700         4            B          65.000000

In [15]:
df.assign(ppsqft=lambda d: d.price / d.bedrooms)

   price  size  bedrooms neighborhood     ppsqft
0  200.0  1400         3            A  66.666667
1  180.0  1200         2            A  90.000000
2  250.0  1600         3            B  83.333333
3  300.0  1800         4            B  75.000000
4    NaN  1500         3            A        NaN
5  220.0  1550         3            B  73.333333
6  260.0  1700         4            B  65.000000

## 6. Sorting Rows (dplyr::arrange)

In R:
```r
arrange(df, price)
```

**TODO:**  
1. Sort `df` by `price` (ascending)  
2. Sort `df` by `price` (descending)

In [16]:
df.sort_values('price')

   price  size  bedrooms neighborhood
1  180.0  1200         2            A
0  200.0  1400         3            A
5  220.0  1550         3            B
2  250.0  1600         3            B
6  260.0  1700         4            B
3  300.0  1800         4            B
4    NaN  1500         3            A

In [17]:
df.sort_values('price', ascending=False)

   price  size  bedrooms neighborhood
3  300.0  1800         4            B
6  260.0  1700         4            B
2  250.0  1600         3            B
5  220.0  1550         3            B
0  200.0  1400         3            A
1  180.0  1200         2            A
4    NaN  1500         3            A

## 7. Grouping and Aggregation

In R:
```r
df %>%
  group_by(neighborhood) %>%
  summarize(mean_price = mean(price, na.rm = TRUE))
```

**TODO:** Reproduce the summary above in pandas.

In [22]:
(df
 .groupby("neighborhood")
 .agg(mean_price=("price", "mean"))
)

              mean_price
neighborhood
A                  190.0
B                  257.5

## 8. Method Chaining (Pipe Mindset)

Pandas supports method chaining, similar to `%>%` in R.

**TODO:** Using chaining, compute:
- **Filter:** `price > 200`  
- **Mutate:** `price_per_sqft = price / size`  
- **Group by** `neighborhood`  
- **Summarize:** average `price_per_sqft`

In [31]:
(df
.query("price > 200")
.assign(price_per_sqft=lambda d: d.price / d.size)
.groupby('neighborhood')
.agg(mean_price_per_sqft=('price_per_sqft', 'mean'))
)

              mean_price_per_sqft
neighborhood
B                        16.09375

In [34]:
df[df['neighborhood'] == 'A']

   price  size  bedrooms neighborhood
0  200.0  1400         3            A
1  180.0  1200         2            A
4    NaN  1500         3            A

## 9. Missing Data

**TODO:**  
1. **Identify** which values are missing  
2. **Drop** rows with missing values  
3. **Fill** missing prices with the mean price  

**Question:** When is dropping missing data reasonable? When is it risky?

In [35]:
	pd.isna(df)

   price   size  bedrooms  neighborhood
0  False  False     False         False
1  False  False     False         False
2  False  False     False         False
3  False  False     False         False
4   True  False     False         False
5  False  False     False         False
6  False  False     False         False

In [38]:
df.dropna()

   price  size  bedrooms neighborhood
0  200.0  1400         3            A
1  180.0  1200         2            A
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

In [40]:
df.fillna(df['price'].mean)

,price,size,bedrooms,neighborhood
0,200.0,1400,3,A
1,180.0,1200,2,A
2,250.0,1600,3,B
3,300.0,1800,4,B
4,<bound method Series.mean of 0 200.0\n1 ...,1500,3,A
5,220.0,1550,3,B
6,260.0,1700,4,B

## 10. Common Pitfalls for R Users

- Boolean filtering requires **parentheses** when combining conditions.  
- `groupby()` does nothing until you **aggregate**.  
- Watch out for **chained assignment** warnings (use `.loc` or single assignment).

## 11. Active Learning Exercise (15–20 min)

**R pipeline:**
```r
df %>%
  filter(size > 1400) %>%
  mutate(price_per_sqft = price / size) %>%
  group_by(neighborhood) %>%
  summarize(avg_ppsqft = mean(price_per_sqft, na.rm = TRUE))
```

**TASK:** Translate the pipeline above into pandas using method chaining. Write clean, readable code.

In [41]:
(df
 .query("size > 1400")
 .assign(price_per_sqft=lambda d: d.price / d.size)
 .groupby("neighborhood")
 .agg(avg_ppsqft=("price_per_sqft", "mean"))
)

              avg_ppsqft
neighborhood
A                    NaN
B                 12.875

## 12. Wrap-Up Reflection

In 2–3 sentences:
- What feels **most similar** to dplyr?  
- What feels **most different**?  
- What do you find **confusing** so far?