<a href="https://colab.research.google.com/github/JordanBaker78/Data201_JordanBaker/blob/main/week2_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 2 – Data Wrangling with pandas

In [13]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/JordanBaker78/Data201_JordanBaker/refs/heads/main/housing.csv")

In [15]:
df.head()

   listing_id    price         size  bedrooms neighborhood          type
0      100001  1500000  1280.741760       1.0       Suburb     Townhouse
1      100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2      100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3      100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4      100005  1500000  1243.751760       1.0     Downtown   MultiFamily

#Part A
Using **one chained expression**, create a summary table that:

1. Keeps only observations where `price > 250000`
2. Keeps only homes with `size > 1000`
3. Creates a new variable:
   - `price_per_sqft = price / size`
4. Groups by `neighborhood`
5. Computes:
   - mean of `price_per_sqft`
   - median of `price_per_sqft`
   - count of homes
6. Sorts the result by mean `price_per_sqft` (descending)

In [14]:
(df
.query("price > 250000 and size > 1000")
.assign(price_per_sqft=lambda d: d.price / d.size)
.groupby('neighborhood')
.agg(
    mean_price_per_sqft=('price_per_sqft', 'mean'),
    median_price_per_sqft=('price_per_sqft', 'median'),
    count_homes=('listing_id', 'count')
)
.sort_values('mean_price_per_sqft', ascending=False)
)

              mean_price_per_sqft  median_price_per_sqft  count_homes
neighborhood
Downtown               505.050505             505.050505           99
Suburb                 505.050505             505.050505          157
Uptown                 505.050505             505.050505           99
Waterfront             505.050505             505.050505           48
Midtown                505.050505             505.050505           92

# Part B – Translation to dplyr

In a Markdown cell, write the equivalent **dplyr** code that performs the same transformation.

Your R pipeline should include:

- `filter()`
- `mutate()`
- `group_by()`
- `summarise()`
- `arrange()`

```
df %>%
  mutate(price_per_sqft = price/size) %>%
  group_by(neighborhood) %>%
  summarize(mean_price_per_sqft=(price_per_sqft, mean)
  median_price_per_sqft=(price_per_sqft, 'median),
  count=(listing_id, count) %>%
  arrange(mean_price_per_sqft, ascending=False)
  ```

### Reflection (3–6 sentences)

Answer:

- Which syntax feels clearer for you — pandas chaining or dplyr pipelines?
- What feels similar between them?
- What feels different?

The chaining feels a little cleaner to me, maybe just because I think the '%>%' symbol is annoying to include every line and the parenthesis make more sense. Both are similar in the way that the code is executed on the same lines and are executed the same. However, the terms are different and to me, pandas looks a little more complicated, but feels more like proper code and is easier to understand.

# Part C – Boolean Logic Debugging

The following code produces an error:

```python
df[df["price"] > 250000 & df["size"] > 1000]
```

### Tasks

1. Fix the code.
2. Explain **why** the error occurs.
3. Rewrite the filter using `.query()` instead.

In [21]:
df[(df["price"] > 250000) & (df["size"] > 1000)]
#The error ocurs becuase there needs to be parentheses around each argument.
df.query("price > 250000 and size > 1000")
#.query works a lot better in this case and is much easier to write.

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

# Part D – Short Concept Questions

Answer briefly (2–4 sentences each):

1. Why must we wrap each condition in parentheses when using `&` in pandas?
2. What is the advantage of method chaining over creating many temporary DataFrames?
3. In `.agg(mean_price=("price", "mean"))`, what does `"price"` represent? What does `"mean"` represent?
4. When you `groupby("neighborhood")`, why does `neighborhood` appear on the left (index) in the result table?

1. The parentheses are important so that pandas knows what the arguments are. The parentheses group each argument so the can can be executed properly. Without the parentheses, an erro will occur.
2. Method chaining allows an entire block of code to execute the code much easier. It is faster and put less stress on the program
3. In `.agg(mean_price=("price", "mean"))`, "price" represents the data that is in the column "price". "Mean" is the average number of all the data in that column.
4. When using `.groupby()`, whatever is inside the paretheses is considered the index. The index always is the 1st (or 0th) column of a table.